df <- read.csv("Spotify_Youtube_Clean.csv", fileEncoding="UTF-8-BOM", check.names=TRUE)
cat("rows:", nrow(df), "\n")
cat("class official_video:", class(df$official_video), "\n")
print(table(df$official_video, useNA="always"))
cat("class Licensed:", class(df$Licensed), "\n")
print(table(df$Licensed, useNA="always"))
cat("ln_Stream NA:", sum(is.na(df$ln_Stream)), " finite:", sum(is.finite(df$ln_Stream)), "\n")
cat("ln_Views NA:", sum(is.na(df$ln_Views)), " finite:", sum(is.finite(df$ln_Views)), "\n")
cat("Stream==0:", sum(df$Stream==0, na.rm=TRUE), " Views==0:", sum(df$Views==0, na.rm=TRUE), "\n")
cat("Album_type levels:", paste(names(table(df$Album_type)), collapse=", "), "\n")
